name: carla37
channels:
  - delichon
  - fastai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=36.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.2.0
  - elementpath=3.0.2
  - entrypoints=0.4
  - ephem=4.1.2
  - eventlet=0.33.0
  - flit-core=3.7.1
  - fonttools=4.29.0
  - freetype=2.10.4
  - geos=3.10.2
  - greenlet=1.1.2
  - gym=0.21.0
  - hydra-core=1.3.2
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.10.1
  - importlib_metadata=4.10.1
  - importlib_resources=5.7.1
  - iniconfig=1.1.1
  - intel-openmp=2022.0.0
  - ipykernel=6.12.1
  - ipython=7.32.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter_client=7.2.1
  - jupyter_core=4.9.2
  - jupyter_server=1.16.0
  - jupyterlab=3.3.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.13.0
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.8
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=0.3.7
  - nbclient=0.6.0
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - networkx=2.2
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - numexpr=2.8.0
  - numpy=1.21.5
  - olefile=0.46
  - opencv-python-headless=4.7.0.68
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=22.0.2
  - pluggy=1.0.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - py=1.11.0
  - pycparser=2.21
  - pygame=1.9.6
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.7.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.7
  - pytz=2021.3
  - pywin32=303
  - pywinpty=2.0.5
  - pyyaml=5.3.1
  - pyzmq=22.3.0
  - qt=5.12.9
  - requests=2.27.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=60.6.0
  - shapely=1.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.37.0
  - statsmodels=0.13.1
  - tabulate=0.9.0
  - tbb=2021.5.0
  - terminado=0.13.3
  - tinycss2=1.1.1
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.0.1
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xmlschema=2.2.0
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - carla==0.9.13
    - py-trees==0.8.3
    - pydot==1.4.2
    - simple-watchdog-timer==0.1.1
    - pygame==1.9.6
    - dacaite==1.8.1
    - tti-dataset-tools==0.1.11
prefix: C:\Users\adhocmaster\anaconda3\envs\carla37
