name: carla37
channels:
  - cctbx202008
  - conda-forge
  - intel
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - click=7.1.2
  - cryptography=3.1.1
  - cycler=0.11.0
  - dbus=1.13.18
  - dnspython=1.16.0
  - eventlet=0.29.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - geos=3.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - greenlet=0.4.17
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - monotonic=1.5
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1h
  - packaging=21.3
  - pandas=1.2.3
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.7.9
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.1.2
  - scipy=1.7.3
  - seaborn=0.11.0
  - setuptools=58.0.4
  - shapely=1.7.1
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - carla==0.9.13
    - pygame==1.9.6
    - tti-dataset-tools==0.1.11
prefix: /home/muktadir/anaconda3/envs/carla37
