name: carla37
channels:
  - anaconda
  - delichon
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=36.0.1
  - cycler=0.11.0
  - dnspython=2.2.0
  - eventlet=0.33.0
  - fonttools=4.29.0
  - freetype=2.10.4
  - geos=3.10.2
  - greenlet=1.1.2
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.10.1
  - importlib_metadata=4.10.1
  - iniconfig=1.1.1
  - intel-openmp=2022.0.0
  - jbig=2.1
  - jpeg=9e
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.8
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.3.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - networkx=2.6.3
  - numexpr=2.8.0
  - numpy=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.3.5
  - patsy=0.5.2
  - pillow=8.4.0
  - pip=22.0.2
  - pluggy=1.0.0
  - py=1.11.0
  - pycparser=2.21
  - pygame=1.9.6
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pytest=6.2.5
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - pyyaml=5.3.1
  - qt=5.12.9
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=60.6.0
  - shapely=1.8.0
  - six=1.16.0
  - sqlite=3.37.0
  - statsmodels=0.13.1
  - tbb=2021.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.1
  - typing_extensions=4.0.1
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.1.7
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - carla==0.9.13
prefix: C:\Users\adhocmaster\anaconda3\envs\carla37
